### ISSUE TITLE
关于Activity重建时异常闪退问题

### ISSUE THREAD

**Issue by Fomovet** [vitaviva/fragivity#49]
版本： 0.2.9

复现Demo地址：https://github.com/Fomovet/MyApplication

问题描述：App运行后去修改xml界面中的文字，再使用Android Studio的Apply Changes Restart Activity重建预览时会出现异常闪退

```
2021-08-06 00:43:38.225 26009-26009/com.example.myapplication E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.myapplication, PID: 26009
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.myapplication/com.example.myapplication.MainActivity}: java.lang.IllegalStateException: Restoring the Navigation back stack failed: destination 112561190 cannot be found from the current destination NavGraph(0x0) startDestination={Destination(0x38d121c) label=com.example.myapplication.HomeFragment class=com.example.myapplication.HomeFragment}
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3318)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3429)
        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5481)
        at android.app.ActivityThread.-wrap19(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2015)
        at android.os.Handler.dispatchMessage(Handler.java:109)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7555)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)
     Caused by: java.lang.IllegalStateException: Restoring the Navigation back stack failed: destination 112561190 cannot be found from the current destination NavGraph(0x0) startDestination={Destination(0x38d121c) label=com.example.myapplication.HomeFragment class=com.example.myapplication.HomeFragment}
        at androidx.navigation.NavController.onGraphCreated(NavController.java:619)
        at androidx.navigation.NavController.setGraph(NavController.java:592)
        at androidx.navigation.NavController.setGraph(NavController.java:572)
        at com.github.fragivity.FragivityUtil__ActionLoadRootKt.loadRootInternal$FragivityUtil__ActionLoadRootKt(ActionLoadRoot.kt:89)
        at com.github.fragivity.FragivityUtil__ActionLoadRootKt.loadRoot(ActionLoadRoot.kt:53)
        at com.github.fragivity.FragivityUtil.loadRoot(Unknown Source:1)
        at com.github.fragivity.FragivityUtil__ActionLoadRootKt.loadRoot(ActionLoadRoot.kt:48)
        at com.github.fragivity.FragivityUtil.loadRoot(Unknown Source:1)
        at com.github.fragivity.Fragivity.loadRoot(Fragivity.kt:17)
        at com.example.myapplication.MainActivity.onCreate(MainActivity.java:20)
        at android.app.Activity.performCreate(Activity.java:7343)
        at android.app.Activity.performCreate(Activity.java:7333)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1219)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3271)
```

**Comment by qdsfdhvh** [comment]
试下这个依赖有没有修复，可能和#48是一个问题
```gradle
 api 'com.github.vitaviva.fragivity:core:0af27f2e86'
```

**Comment by Fomovet** [comment]
使用 `com.github.vitaviva.fragivity:core:0af27f2e86`版本测试问题已修复
