### ISSUE TITLE
 0.3.1 版本 navigator.push 携带参数并设置 popSelf = true 会闪退 

### ISSUE THREAD

**Issue by jarryleo** [vitaviva/fragivity#59]
```
java.lang.NoSuchFieldError: No field mBackStack of type Ljava/util/Deque; in class Landroidx/navigation/NavController; or its superclasses (declaration of 'androidx.navigation.NavController' appears in /data/app/com.whitewolfx.tools-2/base.apk:classes21.dex)
        at androidx.navigation.ExtKt.removeLastBackStackEntry(Ext.kt:20)
        at com.github.fragivity.FragivityUtil__ActionPushKt.pushInternal$FragivityUtil__ActionPushKt(ActionPush.kt:80)
        at com.github.fragivity.FragivityUtil__ActionPushKt.pushInternal$FragivityUtil__ActionPushKt$default(ActionPush.kt:63)
        at com.github.fragivity.FragivityUtil__ActionPushKt.push(ActionPush.kt:39)
        at com.github.fragivity.FragivityUtil.push(Unknown Source)
        at com.github.fragivity.FragivityUtil__ActionPushKt.push(ActionPush.kt:31)
        at com.github.fragivity.FragivityUtil.push(Unknown Source)
```

**Comment by qdsfdhvh** [comment]
应该是navigation的版本问题，最近会尝试适配新版本
